"""Model metadata and ingestion value rules. No database required."""

import datetime as dt
from decimal import Decimal
from typing import Any

import pytest
from sqlalchemy import BigInteger, Date, DateTime, Index, Numeric, Text, UniqueConstraint
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from app.models import Base
from app.quality.moisture.ingestion import (
    compute_source_row_hash,
    identifier,
    measurement,
    source_date,
    to_measurement_values,
)
from app.quality.moisture.models import FinishingMeasurement

table = FinishingMeasurement.__table__


def source_row(**overrides: Any) -> dict[str, Any]:
    row: dict[str, Any] = {
        "DATE": dt.date(2026, 9, 1),
        "CAMPNO": "26101",
        "LOT": "A260901-01",
        "Location": "Silo 1",
        "PRODUCT": "PRD-A",
        "AvgOfMOISTURE": 0.4,
        "AvgOfCOLOR": 40.0,
        "AvgOfCombined_BD": 0.7,
    }
    row.update(overrides)
    return row


# Metadata ---------------------------------------------------------------------


def test_table_is_registered_in_quality_schema() -> None:
    assert table.schema == "quality"
    assert table.name == "finishing_measurements"
    assert Base.metadata.tables["quality.finishing_measurements"] is table


@pytest.mark.parametrize(
    ("column", "type_", "nullable"),
    [
        ("id", BigInteger, False),
        ("source_date", Date, False),
        ("campaign_no", Text, True),
        ("lot", Text, True),
        ("location", Text, True),
        ("product", Text, True),
        ("avg_moisture", Numeric, True),
        ("avg_color", Numeric, True),
        ("avg_combined_bd", Numeric, True),
        ("source_system", Text, False),
        ("source_row_hash", Text, False),
        ("synced_at", DateTime, False),
        ("created_at", DateTime, False),
    ],
)
def test_column_types_and_nullability(column: str, type_: type, nullable: bool) -> None:
    col = table.c[column]
    assert isinstance(col.type, type_)
    assert col.nullable is nullable


def test_measurements_are_unconstrained_numeric() -> None:
    for name in ("avg_moisture", "avg_color", "avg_combined_bd"):
        column_type = table.c[name].type
        assert column_type.precision is None
        assert column_type.scale is None
        assert column_type.asdecimal is True


def test_primary_key_is_bigint_identity() -> None:
    assert [c.name for c in table.primary_key.columns] == ["id"]
    assert table.c.id.identity is not None


def test_timestamps_are_timezone_aware() -> None:
    assert table.c.synced_at.type.timezone is True
    assert table.c.created_at.type.timezone is True
    assert table.c.created_at.server_default is not None
    assert table.c.synced_at.server_default is None


def test_unique_constraint_on_source_system_and_hash() -> None:
    uniques = [c for c in table.constraints if isinstance(c, UniqueConstraint)]
    assert len(uniques) == 1
    assert [c.name for c in uniques[0].columns] == ["source_system", "source_row_hash"]
    assert uniques[0].name == "uq_finishing_measurements_source_system_source_row_hash"


def _index_ddl(name: str) -> str:
    index = next(i for i in table.indexes if isinstance(i, Index) and i.name == name)
    return str(CreateIndex(index).compile(dialect=postgresql.dialect()))


def test_indexes_support_recent_and_product_queries() -> None:
    assert {i.name for i in table.indexes} == {
        "ix_finishing_measurements_source_date_desc",
        "ix_finishing_measurements_product_source_date",
        "ix_finishing_measurements_product_lot",
    }
    assert "(source_date DESC, id DESC)" in _index_ddl("ix_finishing_measurements_source_date_desc")
    assert "(product, source_date DESC)" in _index_ddl(
        "ix_finishing_measurements_product_source_date"
    )
    assert "(product, lot)" in _index_ddl("ix_finishing_measurements_product_lot")


def test_postgres_ddl() -> None:
    ddl = str(CreateTable(table).compile(dialect=postgresql.dialect()))
    assert "CREATE TABLE quality.finishing_measurements" in ddl
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY" in ddl
    assert "avg_moisture NUMERIC," in ddl
    assert "created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL" in ddl


# Value conversion -----------------------------------------------------------------


def test_null_measurement_stays_null_and_zero_stays_zero() -> None:
    assert measurement(None) is None
    assert measurement(0) == Decimal(0)
    assert measurement(0.0) == Decimal(0)
    assert measurement(0.0) is not None


def test_float_measurements_keep_their_exact_source_value() -> None:
    value = 0.43333333333333335
    stored = measurement(value)
    assert stored == Decimal("0.43333333333333335")
    assert float(stored) == value


@pytest.mark.parametrize("bad", [float("nan"), float("inf"), "abc", True, [1]])
def test_invalid_measurements_are_rejected(bad: Any) -> None:
    with pytest.raises((ValueError, TypeError)):
        measurement(bad)


def test_identifiers_are_text_and_not_normalized() -> None:
    assert identifier(26101) == "26101"
    assert identifier("  Silo 1 ") == "  Silo 1 "
    assert identifier(None) is None
    with pytest.raises(TypeError):
        identifier(1.5)


def test_source_date_rejects_a_real_time_component() -> None:
    assert source_date(dt.datetime(2026, 9, 1)) == dt.date(2026, 9, 1)
    assert source_date("2026-09-01") == dt.date(2026, 9, 1)
    with pytest.raises(ValueError, match="time component"):
        source_date(dt.datetime(2026, 9, 1, 13, 30))


def test_insert_values_require_timezone_aware_sync_time() -> None:
    with pytest.raises(ValueError, match="timezone-aware"):
        to_measurement_values(source_row(), source_system="access", synced_at=dt.datetime.now())

    values = to_measurement_values(
        source_row(AvgOfCOLOR=None), source_system="access", synced_at=dt.datetime.now(dt.UTC)
    )
    assert values["avg_color"] is None
    assert values["avg_moisture"] == Decimal("0.4")


# Source row hash ----------------------------------------------------------------


def test_hash_is_stable_and_hex_sha256() -> None:
    first = compute_source_row_hash(source_row())
    assert first == compute_source_row_hash(source_row())
    assert len(first) == 64
    int(first, 16)


def test_hash_distinguishes_null_from_zero() -> None:
    assert compute_source_row_hash(source_row(AvgOfMOISTURE=None)) != compute_source_row_hash(
        source_row(AvgOfMOISTURE=0)
    )


def test_hash_treats_equal_values_of_different_types_equally() -> None:
    base = compute_source_row_hash(source_row())
    assert base == compute_source_row_hash(
        source_row(
            CAMPNO=26101,
            DATE=dt.datetime(2026, 9, 1),
            AvgOfMOISTURE=Decimal("0.40"),
            AvgOfCOLOR=40,
        )
    )


def test_hash_preserves_text_exactly() -> None:
    base = compute_source_row_hash(source_row())
    assert base != compute_source_row_hash(source_row(Location="SILO 1"))
    assert base != compute_source_row_hash(source_row(Location="Silo 1 "))


def test_hash_changes_when_any_field_changes() -> None:
    base = compute_source_row_hash(source_row())
    for field, value in {
        "DATE": dt.date(2026, 9, 2),
        "CAMPNO": "26102",
        "LOT": "other",
        "PRODUCT": "PRD-B",
        "AvgOfMOISTURE": 0.41,
        "AvgOfCOLOR": 40.5,
        "AvgOfCombined_BD": 0.71,
    }.items():
        assert compute_source_row_hash(source_row(**{field: value})) != base, field


def test_hash_requires_every_source_field() -> None:
    row = source_row()
    del row["LOT"]
    with pytest.raises(ValueError, match="LOT"):
        compute_source_row_hash(row)
