/**
 * The platform's permission catalog, as the API defines it
 * (app/core/permissions.py). The interface uses permissions only to decide what
 * to show; the API checks every request itself.
 */
export const PERMISSIONS = [
  "app.view",
  "users.view",
  "users.create",
  "users.edit",
  "users.activate",
  "users.deactivate",
  "users.assignRoles",
  "users.manage",
  "roles.view",
  "roles.create",
  "roles.edit",
  "roles.delete",
  "roles.assignPermissions",
  "roles.manage",
  "audit.view",
  "quality.view",
  "quality.admin",
  "qualityCost.view",
  "qualityCost.create",
  "qualityCost.edit",
  "qualityCost.delete",
  "qualityCost.assign",
  "qualityCost.confirmFinancial",
  "qualityCost.close",
  "qualityCost.export",
  "car.view",
  "car.create",
  "car.edit",
  "car.delete",
  "car.assign",
  "car.manageActions",
  "car.completeAction",
  "car.reviewEffectiveness",
  "car.approve",
  "car.close",
  "car.reopen",
  "car.export",
  "car.admin",
  "safety.view",
  "safety.admin",
  "safetyRecord.view",
  "safetyRecord.create",
  "safetyRecord.edit",
  "safetyRecord.delete",
  "safetyRecord.assign",
  "safetyRecord.review",
  "safetyRecord.approve",
  "safetyRecord.close",
  "safetyRecord.reopen",
  "safetyRecord.export",
  "incident.view",
  "incident.create",
  "incident.edit",
  "incident.delete",
  "incident.assign",
  "incident.classify",
  "incident.investigate",
  "incident.review",
  "incident.approve",
  "incident.close",
  "incident.reopen",
  "incident.export",
  "nearMiss.view",
  "nearMiss.create",
  "nearMiss.edit",
  "nearMiss.delete",
  "nearMiss.assign",
  "nearMiss.investigate",
  "nearMiss.review",
  "nearMiss.close",
  "nearMiss.reopen",
  "nearMiss.export",
  "safetyObservation.view",
  "safetyObservation.create",
  "safetyObservation.edit",
  "safetyObservation.delete",
  "safetyObservation.assign",
  "safetyObservation.review",
  "safetyObservation.close",
  "safetyObservation.export",
  "safetyAction.view",
  "safetyAction.create",
  "safetyAction.edit",
  "safetyAction.delete",
  "safetyAction.assign",
  "safetyAction.complete",
  "safetyAction.verify",
  "safetyAction.approve",
  "safetyAction.close",
  "safetyAction.reopen",
  "safetyAction.export",
  "safetyInvestigation.view",
  "safetyInvestigation.create",
  "safetyInvestigation.edit",
  "safetyInvestigation.assign",
  "safetyInvestigation.complete",
  "safetyInvestigation.review",
  "safetyInvestigation.approve",
  "safetyInvestigation.close",
  "safetyInvestigation.reopen",
  "safetyInvestigation.export",
  "qualityDashboard.view",
  "safetyDashboard.view",
  "assignments.viewOwn",
  "assignments.updateOwn",
  "assignments.viewAll",
  "assignments.reassign",
  "attachments.view",
  "attachments.upload",
  "attachments.deleteOwn",
  "attachments.deleteAny",
  "comments.view",
  "comments.create",
  "comments.editOwn",
  "comments.deleteOwn",
  "comments.moderate",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const KNOWN = new Set<string>(PERMISSIONS);

export function isPermission(value: string): value is Permission {
  return KNOWN.has(value);
}

/** What a page or menu item needs: every permission in `all`, and at least one in `any`. */
export type Requirement = { all?: readonly Permission[]; any?: readonly Permission[] };

export function meets(granted: ReadonlySet<Permission>, requirement: Requirement | undefined): boolean {
  if (!requirement) return true;
  const all = requirement.all ?? [];
  const any = requirement.any ?? [];
  return all.every((p) => granted.has(p)) && (any.length === 0 || any.some((p) => granted.has(p)));
}
